import type { WeaponDef } from "../types";

/** GoldenEye-flavored arsenal. Damage numbers assume guard HP of 60. */
export const WEAPONS: Record<string, WeaponDef> = {
  slappers: {
    id: "slappers",
    name: "SLAPPERS",
    short: "SLAPPERS",
    slot: 1,
    kind: "melee",
    damage: 30,
    headMult: 1,
    pellets: 1,
    fireRate: 1.8,
    auto: false,
    magSize: 0,
    ammo: null,
    spread: 0,
    aimSpread: 0,
    noiseRadius: 0,
    reloadTime: 0,
    range: 0,
    zoomFov: 0,
    silenced: true,
    kick: 0,
    bloomAdd: 0,
    penetrate: false,
    meleeRange: 1.5
  },
  knife: {
    id: "knife",
    name: "COMBAT KNIFE",
    short: "KNIFE",
    slot: 1,
    kind: "melee",
    damage: 65,
    headMult: 1,
    pellets: 1,
    fireRate: 1.4,
    auto: false,
    magSize: 0,
    ammo: null,
    spread: 0,
    aimSpread: 0,
    noiseRadius: 0,
    reloadTime: 0,
    range: 0,
    zoomFov: 0,
    silenced: true,
    kick: 0,
    bloomAdd: 0,
    penetrate: false,
    meleeRange: 1.7
  },
  pp9: {
    id: "pp9",
    name: "PP9 (SILENCED)",
    short: "PP9",
    slot: 1,
    kind: "gun",
    damage: 25,
    headMult: 4,
    pellets: 1,
    fireRate: 4,
    auto: false,
    magSize: 7,
    ammo: "9mm",
    spread: 0.012,
    aimSpread: 0.004,
    noiseRadius: 7,
    reloadTime: 1.3,
    range: 80,
    effectiveRange: 26,
    zoomFov: 0,
    silenced: true,
    kick: 0.0045,
    bloomAdd: 0.004,
    penetrate: true
  },
  dd4: {
    id: "dd4",
    name: "DD4 DOSTOVEI",
    short: "DD4",
    slot: 2,
    kind: "gun",
    damage: 34,
    headMult: 4,
    pellets: 1,
    fireRate: 3,
    auto: false,
    magSize: 8,
    ammo: "9mm",
    spread: 0.02,
    aimSpread: 0.007,
    noiseRadius: 30,
    reloadTime: 1.3,
    range: 80,
    effectiveRange: 28,
    zoomFov: 0,
    silenced: false,
    kick: 0.009,
    bloomAdd: 0.005,
    penetrate: true
  },
  klobb: {
    id: "klobb",
    name: "VZ-61 SKORPION",
    short: "VZ-61",
    slot: 3,
    kind: "gun",
    damage: 9,
    headMult: 3,
    pellets: 1,
    fireRate: 11,
    auto: true,
    magSize: 20,
    ammo: "9mm",
    spread: 0.05,
    aimSpread: 0.03,
    noiseRadius: 28,
    reloadTime: 1.7,
    range: 60,
    effectiveRange: 18,
    zoomFov: 0,
    silenced: false,
    kick: 0.003,
    bloomAdd: 0.003,
    penetrate: true
  },
  klobb_dual: {
    id: "klobb_dual",
    name: "DUAL VZ-61",
    short: "2x VZ-61",
    slot: 3,
    kind: "gun",
    damage: 9,
    headMult: 3,
    pellets: 1,
    fireRate: 18,
    auto: true,
    magSize: 40,
    ammo: "9mm",
    spread: 0.062,
    aimSpread: 0.045,
    noiseRadius: 30,
    reloadTime: 2.4,
    range: 60,
    effectiveRange: 16,
    zoomFov: 0,
    silenced: false,
    kick: 0.0045,
    bloomAdd: 0.0035,
    penetrate: true
  },
  kr7: {
    id: "kr7",
    name: "KR-7 SOVIET",
    short: "KR-7",
    slot: 3,
    kind: "gun",
    damage: 16,
    headMult: 3,
    pellets: 1,
    fireRate: 9,
    auto: true,
    magSize: 30,
    ammo: "rifle",
    spread: 0.035,
    aimSpread: 0.016,
    noiseRadius: 32,
    reloadTime: 2.0,
    range: 90,
    effectiveRange: 42,
    zoomFov: 0,
    silenced: false,
    kick: 0.0055,
    bloomAdd: 0.0035,
    penetrate: true
  },
  shotgun: {
    id: "shotgun",
    name: "KS-23 SHOTGUN",
    short: "KS-23",
    slot: 4,
    kind: "gun",
    damage: 11,
    headMult: 2,
    pellets: 8,
    fireRate: 1.1,
    auto: false,
    magSize: 5,
    ammo: "shells",
    spread: 0.065,
    aimSpread: 0.045,
    noiseRadius: 32,
    reloadTime: 2.6,
    range: 40,
    effectiveRange: 14,
    zoomFov: 0,
    silenced: false,
    kick: 0.026,
    bloomAdd: 0.01,
    penetrate: false
  },
  sniper: {
    id: "sniper",
    name: "SVD-63 SNIPER",
    short: "SVD",
    slot: 5,
    kind: "gun",
    damage: 90,
    headMult: 4,
    pellets: 1,
    fireRate: 0.55,
    auto: false,
    magSize: 5,
    ammo: "rifle",
    spread: 0.05,
    aimSpread: 0.0006,
    noiseRadius: 36,
    reloadTime: 2.8,
    range: 160,
    zoomFov: 14,
    silenced: false,
    kick: 0.04,
    bloomAdd: 0,
    penetrate: true,
    scopeOverlay: true
  },
  golden: {
    id: "golden",
    name: "THE GOLDEN GUN",
    short: "GOLDEN",
    slot: 2,
    kind: "gun",
    damage: 999,
    headMult: 1,
    pellets: 1,
    fireRate: 0.7,
    auto: false,
    magSize: 1,
    ammo: "golden",
    spread: 0.008,
    aimSpread: 0.002,
    noiseRadius: 34,
    reloadTime: 1.9,
    range: 100,
    effectiveRange: 45,
    zoomFov: 0,
    silenced: false,
    kick: 0.02,
    bloomAdd: 0,
    penetrate: true
  },
  railgun: {
    id: "railgun",
    name: "GAUSS PROTOTYPE",
    short: "GAUSS",
    slot: 5,
    kind: "gun",
    damage: 200,
    headMult: 2,
    pellets: 1,
    fireRate: 0.8,
    auto: false,
    magSize: 3,
    ammo: "rail",
    spread: 0.003,
    aimSpread: 0.0008,
    noiseRadius: 26,
    reloadTime: 2.4,
    range: 140,
    zoomFov: 20,
    silenced: false,
    kick: 0.032,
    bloomAdd: 0,
    penetrate: true
  },
  grenade: {
    id: "grenade",
    name: "HAND GRENADE",
    short: "GRENADE",
    slot: 6,
    kind: "thrown",
    damage: 130,
    headMult: 1,
    pellets: 1,
    fireRate: 0.9,
    auto: false,
    magSize: 0,
    ammo: "grenade",
    spread: 0,
    aimSpread: 0,
    noiseRadius: 45,
    reloadTime: 0,
    range: 0,
    zoomFov: 0,
    silenced: false,
    kick: 0,
    bloomAdd: 0,
    penetrate: false
  },
  mines: {
    id: "mines",
    name: "REMOTE MINES",
    short: "MINES",
    slot: 7,
    kind: "mine",
    damage: 150,
    headMult: 1,
    pellets: 1,
    fireRate: 1.5,
    auto: false,
    magSize: 0,
    ammo: "mine",
    spread: 0,
    aimSpread: 0,
    noiseRadius: 45,
    reloadTime: 0,
    range: 3,
    zoomFov: 0,
    silenced: true,
    kick: 0,
    bloomAdd: 0,
    penetrate: false
  },
  camera: {
    id: "camera",
    name: "FIELD CAMERA",
    short: "CAMERA",
    slot: 8,
    kind: "camera",
    damage: 0,
    headMult: 1,
    pellets: 1,
    fireRate: 1.2,
    auto: false,
    magSize: 0,
    ammo: null,
    spread: 0,
    aimSpread: 0,
    noiseRadius: 0,
    reloadTime: 0,
    range: 1.5,
    zoomFov: 45,
    silenced: true,
    kick: 0,
    bloomAdd: 0,
    penetrate: false
  },
  lockpick: {
    id: "lockpick",
    name: "LOCK PICK",
    short: "PICK",
    slot: 8,
    kind: "tool",
    damage: 0,
    headMult: 1,
    pellets: 1,
    fireRate: 1.5,
    auto: false,
    magSize: 0,
    ammo: null,
    spread: 0,
    aimSpread: 0,
    noiseRadius: 0,
    reloadTime: 0,
    range: 2.6,
    zoomFov: 0,
    silenced: true,
    kick: 0,
    bloomAdd: 0,
    penetrate: false
  }
};

export interface SlotGroup {
  /** the digit key that selects this slot */
  key: number;
  /** hotbar label when nothing in the group is owned */
  label: string;
  /** weapon ids in cycle order; pressing the key again cycles owned members */
  members: string[];
}

/** Hotbar slots. One cell per key; pressing the key again cycles the group. */
export const SLOT_GROUPS: SlotGroup[] = [
  { key: 1, label: "MELEE", members: ["slappers", "knife"] },
  { key: 2, label: "PISTOL", members: ["pp9", "dd4", "golden"] },
  { key: 3, label: "AUTO", members: ["klobb", "klobb_dual", "kr7"] },
  { key: 4, label: "SHOTGUN", members: ["shotgun"] },
  { key: 5, label: "SCOPED", members: ["sniper", "railgun"] },
  { key: 6, label: "THROWN", members: ["grenade"] },
  { key: 7, label: "MINES", members: ["mines"] },
  { key: 8, label: "EQUIPMENT", members: ["camera", "lockpick"] }
];

export const SLOT_ORDER = SLOT_GROUPS.flatMap((g) => g.members);
